### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mxr576** [chris-l/generator-restify#4]
Hi!

There is a typo in your README.md , you have forgotten the server.get()'s and server.put()'s closing ")" in the example code. Here is a the fix:

``` javascript
module.exports = function (server) {
  server.get('/info/:param', function (req, res, next) {
  });

  server.put('/info/', function (req, res, next) {
  });
};
```

Thanks for the generator!

Greetings, mxr576

**Comment by chris-l** [comment]
Ok, fixed on this PR e9d9dbc167a2da77b2246f9519622bee7479ad5b!
