### ISSUE TITLE
Update to Restify 4?

### ISSUE THREAD

**Issue by michaelsanford** [chris-l/generator-restify#5]
A number of major improvements and bug-fixes were [brought to `restify` with version 4](https://github.com/restify/node-restify/releases). The currently-stable release is [4.0.3](https://github.com/restify/node-restify/releases/tag/v4.0.3).

Could we consider updating the `restify` installed by this generator?

**Comment by ojengwa** [comment]
I support this update request. Maybe we create a different branch/fork for the project to maintain backward deps.

**Comment by chris-l** [comment]
Done!
