### ISSUE TITLE
missing of cb of the formatters in index.js 

### ISSUE THREAD

**Issue by dnaroma** [chris-l/generator-restify#8]
In `restify >= 4.0.0`, formatters should invoke callback, see https://github.com/restify/node-restify/issues/893 and http://restify.com/#content-negotiation, or the request never ends.

**Comment by Kubuxu** [comment]
Just spent hour debugging it...

**Comment by chris-l** [comment]
Fixed: 60997f205a223d26d503472238aab0ffe81d3e7e
